before_install:
   - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - npm install -g istanbul
  - npm install -g mocha

script: 'make test-cov'
after_success: 'make coveralls'

sudo: false
language: node_js
node_js:
  - "9"
  - "8"
  - "6"
  - "5"
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
